apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pinchflat
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect@kubernetescrd

spec:
  tls:
    - hosts:
        - pinchflat.bootleg.technology
      secretName: tls-cert
  rules:
    - host: pinchflat.bootleg.technology
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: pinchflat
                port:
                  name: http
