apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - borik.yaml
  - calibre.yaml
  - cheesetown.yaml
  - cloudflare-ddns.yaml
  - ergo.yaml
  - grackdb.yaml
  - homeassistant-proxy.yaml
  - hopper.yaml
  - immich.yaml
  - interruption-spotter.yaml
  - litellm.yaml
  - miniflux.yaml
  - netbox.yaml
  - ntv-webcam-scraper.yaml
  - paperless-ngx.yaml
  - pkg-fogo-sh
  - pkg-nit-so.yaml
  - plex-proxy.yaml
  - pollster.yaml
  - scribe.yaml
  - shopkeeper-cts.yaml
  - shopkeeper.yaml
  - skyline.yaml
