apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ergo

resources:
  - namespace.yaml
  - certificate.yaml
  - persistent_volume_claim.yaml

configMapGenerator:
  - name: config
    files:
      - config/ircd.yaml
      - config/ircd.motd
