apiVersion: networking.k8s.io/v1
kind: Ingress

metadata:
  name: cheesetown
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
    traefik.ingress.kubernetes.io/router.middlewares: traefik-https-redirect@kubernetescrd

spec:
  tls:
    - hosts:
        - map.cheesetown.rocks
        - sorter.cheesetown.rocks
      secretName: tls-cert
  rules:
    - host: map.cheesetown.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: map
                port:
                  name: http
    - host: sorter.cheesetown.rocks
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: sorter
                port:
                  name: http
