apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cheesetown

resources:
  - namespace.yaml
  - service-map.yaml
  - service-sorter.yaml
  - endpoints-map.yaml
  - endpoints-sorter.yaml
  - ingress.yaml
