services:
  traefik:
    image: "traefik:v3.5.4"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ingress
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ares_ingress"
      - "--entryPoints.web.address=:80"
    ports:
      # TODO: Set up HTTPS
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
  
  open-webui:
    image: "ghcr.io/open-webui/open-webui:v0.6.34"
    restart: unless-stopped
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ares.internal.bootleg.technology`)"
      - "traefik.http.routers.open-webui.entrypoints=web"
      - "traefik.docker.network=ares_ingress"
    volumes:
      - open-webui-data:/app/backend/data
  
  llama:
    build: ./llama-swap-strix-halo
    restart: unless-stopped
    volumes:
      - /data/models:/models:ro,Z
      - ./llama-swap-config.yaml:/app/config.yaml:ro,Z
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llama.rule=Host(`llama.internal.bootleg.technology`)"
      - "traefik.http.routers.llama.entrypoints=web"
      - "traefik.http.services.llama.loadbalancer.server.port=8080"
      - "traefik.docker.network=ares_ingress"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    security_opt:
      - "seccomp=unconfined"

networks:
  ingress:
  inference:

volumes:
  open-webui-data:
