services:
  traefik:
    image: "traefik:v3.6.2"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - ingress
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=ares_ingress"
      - "--entryPoints.web.address=:80"
    ports:
      # TODO: Set up HTTPS
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro,Z
  
  open-webui:
    image: "ghcr.io/open-webui/open-webui:0.6.40"
    restart: unless-stopped
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.open-webui.rule=Host(`ares.internal.bootleg.technology`)"
      - "traefik.http.routers.open-webui.entrypoints=web"
      - "traefik.docker.network=ares_ingress"
    volumes:
      - open-webui-data:/app/backend/data
  
  llama:
    build: ./llama-swap-strix-halo
    restart: unless-stopped
    volumes:
      - /data/models:/models:ro,Z
      - ./llama-swap-config.yaml:/app/config.yaml:ro,Z
    networks:
      - ingress
      - inference
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llama.rule=Host(`llama.internal.bootleg.technology`)"
      - "traefik.http.routers.llama.entrypoints=web"
      - "traefik.http.services.llama.loadbalancer.server.port=8080"
      - "traefik.docker.network=ares_ingress"
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    security_opt:
      - "seccomp=unconfined"
  
  litellm-db:
    image: postgres:18.1
    restart: unless-stopped
    volumes:
      - litellm-db-data:/var/lib/postgresql
    networks:
      - inference
    env_file:
      - ./litellm-db.env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d litellm -U llmproxy"]
      interval: 1s
      timeout: 5s
      retries: 10
  
  litellm:
    image: ghcr.io/berriai/litellm:v1.80.0-stable
    restart: unless-stopped
    depends_on:
      litellm-db:
        condition: service_healthy
    volumes:
      - ./litellm-config.yaml:/app/config.yaml:ro,Z
    command:
      - "--config=/app/config.yaml"
    networks:
      - ingress
      - inference
    env_file:
      - ./litellm.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.litellm.rule=Host(`llm.internal.bootleg.technology`) || Host(`llm.ops.bootleg.technology`)"
      - "traefik.http.routers.litellm.entrypoints=web"
      - "traefik.http.services.litellm.loadbalancer.server.port=4000"
      - "traefik.docker.network=ares_ingress"

networks:
  ingress:
  inference:

volumes:
  open-webui-data:
  litellm-db-data:
