apiVersion: v1
kind: ConfigMap

metadata:
  name: config

data:
  DB_PATH: "/data/pollster.sqlite"
  BEHIND_REVERSE_PROXY: "true"
  GUILD_IDS: '["497544520695808000", "1327749953971425411"]'
  OWNER_ID: "106162668032802816"
